backend:
  name: git-gateway
  branch: main


media_folder: "src/assets/images/uploads"

public_folder: "/assets/images/uploads"


logo_url: "/assets/images/logo.png"

collections:
  - name: "home"
    label: "Home"
    delete: false
    files:
      - label: "Next Game"
        name: "nextgame"
        file: "index.njk"
        fields:
          - {label: "Base", name: "base", widget: "hidden", default: "layout/base.njk"}
          - {label: "Heim Team Logo", name: "heimteamlogo", widget: "image"}
          - {label: "Heim Team Name", name: "heimteamname", widget: "string"}
          - {label: "Gast Team Logo", name: "gastteamlogo", widget: "image"}
          - {label: "Gast Team Name", name: "gastteamname", widget: "string"}

          - {label: "Start time", name: "start", widget: "datetime", date_format: "DD.MMMM", time_format: "HH:mm", format: "LLL", picker_utc: false}

          - {label: "Maps Link", name: "mapslink", widget: "string"}
