backend:
  name: git-gateway
  branch: main

site_url: https://cologne-smilies.de

media_folder: "src/assets/images/uploads"

public_folder: "/assets/images/uploads"


logo_url: "/assets/images/logo.png"

collections:
  - name: "home"
    label: "Home"
    delete: false
    media_library:
      config:
        multiple: true
    files:
      - label: "Next Game"
        name: "nextgame"
        file: "src/_data/nextgame.json"
        fields:
          - {label: "Base", name: "base", widget: "hidden", default: "layout/base.njk"}
          - {label: "Heim Team Logo", name: "heimteamlogo", widget: "image"}
          - {label: "Heim Team Name", name: "heimteamname", widget: "string"}
          - {label: "Gast Team Logo", name: "gastteamlogo", widget: "image"}
          - {label: "Gast Team Name", name: "gastteamname", widget: "string"}
          - {label: "Tag", name: "day", widget: "date", date_locale: "de", date_format: "Do", picker_utc: false}
          - {label: "Monat", name: "month", widget: "date", date_locale: "de", date_format: "MMM", picker_utc: false}
          - {label: "Zeit", name: "time", widget: "time", date_locale: "de", time_format: "LT", picker_utc: false}
          - {label: "Maps Link", name: "mapslink", widget: "string"}
